### ISSUE TITLE
Error launching .jnlp

### ISSUE THREAD

**Issue by f-ferraro** [rodrigoSantamaria/Voronto#3]
Dear @rodrigoSantamaria, 
Thank you very much for this nice and useful resource. 

I would like to use it but so far I have been unsuccessful to start the program. 

I tried running the .jnlp on Windows 11. 
Javaws is started but after a while I get the following errors: 

Exception tab
```

JNLPException[category: Security Error : Exception: null : LaunchDesc: 
<jnlp codebase="http://vis.usal.es/~visusal/voronto/swt/" href="http://vis.usal.es/~visusal/voronto/swt/voronto.jnlp">
  <information>
    <title>Voronoi</title>
    <vendor>University of Salamanca</vendor>
    <homepage href="http://vis.usal.es/voronto"/>
    <icon href="http://vis.usal.es/~visusal/voronto/images/voronto3.png"/>
    <icon kind="splash" href="http://vis.usal.es/~visusal/voronto/images/splash.png"/>
    <offline-allowed/>
  </information>
  <security>
    <all-permissions/>
  </security>
  <resources>
    <j2se version="1.5+" java-vm-args="-Xmx1024m"/>
  </resources>
  <resources>
    <jar href="voronto.jar" main="true"/>
  </resources>
  <application-desc main-class="es.usal.voronto.control.Voronto"/>
</jnlp> ]
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Launch File tab

```

<?xml version="5.0" encoding="UTF-8"?>
<jnlp codebase="http://vis.usal.es/~visusal/voronto/swt/" href="http://vis.usal.es/~visusal/voronto/swt/voronto.jnlp">
        <information>
                <title>Voronoi</title>
                <vendor>University of Salamanca</vendor>
                <homepage href="http://vis.usal.es/voronto"/>
                <icon href="http://vis.usal.es/~visusal/voronto/images/voronto3.png"/> 
                <icon kind="splash" href="http://vis.usal.es/~visusal/voronto/images/splash.png"/> 
                <offline-allowed/>
        </information>
        <security>
                <all-permissions/>
        </security>
        <resources>
                <j2se version="1.5+" java-vm-args="-Xmx1024m"/>
        </resources>
        <resources>
                <jar href="voronto.jar" main="true"/>
        </resources>
        <application-desc main-class="es.usal.voronto.control.Voronto">
        </application-desc>
</jnlp>
```

I also tried to run it in in Ubuntu 22.04 with similar errors. 

Could you please help me with this? 

Thank you in advance!
Best regards,
Federico

**Comment by rodrigoSantamaria** [comment]
Dear Federico, 
Thanks a lot for considering Voronto :)
If the java web start is not working, you can run the .jar file directly from a terminal with
java -jar voronto.jar

Java version should be 11+, but it will probably run ok with 1.8+
The jar file can be downloaded from http://vis.usal.es/voronto/voronto.jar

I'll check what's wrong with jws and let you know.

Cheers,
Rodrigo

**Comment by f-ferraro** [comment]
Dear Rodrigo, 

Thank you very much for the link and support! :) 

Best regards,
Federico
